services:
  strapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: strapi_monolith
    env_file: .env
    ports:
      - 1337:1337
    volumes:
      - ./strapi:/strapi/
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
